---
- name: Pobierz running-config z urządzeń
  hosts: all
  gather_facts: no  # Zbieranie faktów nie jest potrzebne, więc wyłączamy
  tasks:
    - name: Wykonaj komendę show running-config
      cisco.ios.ios_command:
        commands:
          - do show running-config
      register: utput

    - name: Pokaż running-config w output
      debug:
        var: output
