---
- name: Pobierz running-config z urządzeń
  hosts: all
  gather_facts: no  # Zbieranie faktów nie jest potrzebne, więc wyłączamy
  tasks:
  
    - name: COLLECT ONLY THE CONFIG AND DEFFAULT FACTS
       ios_facts:
         gather_subset:
           - config
       register: config
       
    - name: VIEW CONFIG
       debug:
         var: config